version: '3'
services:
    emailhog:
        image: 'mailhog/mailhog'
        container_name: mailhog
        ports:
            - 1025:1025
        networks:
            - note-app-network
#    mysql:
#        image: 'mysql:8.0.30'
#        environment:
#            - MYSQL_ROOT_PASSWORD=password
#            - MYSQL_DATABASE=seedapp
#        ports:
#            - 3306:3306
#        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#        networks:
#            - note-app-network
volumes:
    esdata1:
        driver: local
networks:
    note-app-network:
        driver: bridge


#run using
#docker-compose -f docker-compose.yml up
# or just docker-compose up
