spring:
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/  #directly serve from src folder instead of target
    web:
        resources:
            static-locations: file:main-app/src/main/resources/static/ #directly serve from src folder instead of target
            cache:
                period: 0
    mvc:
        static-path-pattern: /static/**

    #Access from http://localhost:8080/h2-console/, db url: jdbc:h2:mem:testdb, username: sa
    h2:
        console:
            enabled: true
